#!/bin/bash

# Use awk to count requests per host or IP address
awk '{ requests[$1]++ } END { for (host in requests) print host }' "$@" | \
  sort | \
  uniq -c | \
  sort -nr | \
  awk 'NR <= 11 { print $2 }'

