#!/bin/bash
# This script displays lines in /etc/ssh/sshd_config that start with a letter.

# Use grep with a regular expression to find lines starting with a letter in /etc/ssh/sshd_config
grep "^[A-Za-z]" /etc/ssh/sshd_config

